language: python
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
      #- os: osx
      #language: "generic"
      #env: PYTHON_VERSION=3.6.9
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew install pyenv
    pyenv install $PYTHON_VERSION
    export PYENV_VERSION=$PYTHON
    export PATH="${HOME}/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi
install:
  - pip install cython
  - python setup.py build
script:
  - python setup.py pytest
