language: python
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      language: "generic"
      env: PYTHON_VERSION=3.6.5
before_install: | 
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    pyenv install $PYTHON_VERSION
    pyenv rehash
    pyenv global $PYTHON_VERSION
    pyenv versions
    python --version
  fi
install:
  - pip install cython
  - python setup.py build
script:
  - python setup.py test
