language: python
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
matrix:
  include:
    - os: linux
      python: "3.5"
      env: PYTHON=python
    - os: linux
      python: "3.6"
      env: PYTHON=python
    - os: osx
      language: "generic"
      env:
        - PYTHON_VERSION=3.6.5
        - PYTHON=python3
before_install: | 
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    pyenv install $PYTHON_VERSION
    pyenv rehash
    pyenv global $PYTHON_VERSION
    pyenv versions
    $PYTHON --version
  fi
install:
  - pip install cython
  - $PYTHON setup.py build
script:
  - $PYTHON setup.py test
