language: python
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      language: "generic"
      env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv MACOSX_DEPLOYMENT_TARGET=10.9
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    git clone https://github.com/MacPython/terryfy.git
    # Avoid printing the lines from the script below.
    source terryfy/travis_tools.sh
    get_python_environment $INSTALL_TYPE $VERSION $VENV
  fi
install:
  - pip install cython
  - python setup.py build
script:
  - python setup.py test --addopts='--ignore terryfy'
after_success: |
  if [ "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ]; then
    pip install twine
    # A single linux can do the wheel for other verions
    if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]; then
      # Only one linux builds source istribution 
      python setup.py sdist
      # Generate requirements.txt file
      pip install pipenv
      pipenv lock -r --dev > requirements.txt
      # wheel requires to use an external image
      docker pull $DOCKER_IMAGE
      docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/build-manylinux.sh
      # copy output to sdist
      mkdir -p dist
      cp wheelhouse/*.whl dist
    else
      if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        # Linux creates the source distribution, no need for macos.
        python setup.py bdist_wheel
      else
        exit 0
      fi
    fi
    twine upload --repository-url $PYPI_REPOSITORY_URL -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  fi
