language: python
python:
  - "3.5"
  - "3.6"
cache: pip
matrix:
  include:
    - os: linux
    - os: osx
install:
  - pip install -r requirements.txt
  - python setup.py build
script:
  - python setup.py pytest
