language: python
cache: pip
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      python: "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py build
script:
  - python setup.py pytest
