language: python
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      language: "generic"
      env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    git clone https://github.com/MacPython/terryfy.git
    # Avoid printing the lines from the script below.
    source terryfy/travis_tools.sh
    get_python_environment $INSTALL_TYPE $VERSION $VENV
  fi
install:
  - pip install cython
  - python setup.py build
script:
  - python setup.py test --addopts='--ignore terryfy'
after_success: |
  if [ "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ]; then
    pip install twine
    if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]; then
      python setup.py sdist
    fi
    python setup.py bdist_wheel
    twine upload --repository-url $PYPI_REPOSITORY_URL -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  fi
